# Blog info
blog_name: Simon Chu
slogan: Every moment is a fresh beginning.
url: http://sychoo.github.io

# the typed word setup is under theme/fexo/layout/_partial/home.ejs
# Set avatar (Absolute url and relative url)
avatar: /images/simon.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: Simon, Simon Chu, Chu, 初城羽, 初, Wilkes University, Computer Science, Machine Learning, Full Stack, SVM, Python, Java, Software Development, Apple Developer, Android Developer, Web Developer

home_nav:
  - name: About
    url: /bio
    target_blank: false
    
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开

  - name: Photos
    url: /photos
    target_blank: false #在新页面打开

  - name: Project
    url: /project
    target_blank: false

  - name: Contact
    url: /contact
    target_blank: false

  - name: Resume
    url: /resume
    target_blank: true

# config page nav
page_nav:
  - name: Blog
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: Cat.
    url: /category/
    target_blank: false
  - name: Tags
    url: /tag/
    target_blank: false
  - name: Links
    url: /link/
    target_blank: false
  - name: Me
    url: /contact
    target_blank: false
  - name: Find
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: Index

search_slogan:
  isShow: true # true|fase
  text: Go Explore ~

link_slogan:
  isShow: true # true|fase
  text: Contact me for more information.


# set backtop show or hide
backtop:
  home: false
  archive: true
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: 
# /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: PoiretOne-Regular
# calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics:

# Comment service
disqus_shortname: 
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner



# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置 #icon-weibo
# =========================================================
about: # "contact" in the webpage
  - type: me
    icon: icon-user
    text_value:
    - "Wilkes University '2020"
    - "Computer Science Major, Math Minor"
    - "Full Stack Developer"
  
  - type: Email
    icon: icon-mail
    text_key: Email
    text_value: "chengyu.chu@wilkes.edu"
    text_value_url: mailto:chengyu.chu@wilkes.edu
  
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@sychoo"
    text_value_url: https://github.com/sychoo
  
  - type: Twitter
    icon: icon-twitter
    text_key: Twitter
    text_value: "@realSimonChu"
    text_value_url: http://twitter.com/realSimonChu
 
  - type: heart
    icon: icon-heart
    text_value: Single
 
  - type: location
    icon: icon-location
    text_value: Wilkes-Barre, PA, United States.


link:
  - name: 织网
    info: 身体和灵魂，总有一个在路上
    url: http://zheng-ji.info/
    avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100
  - name: Dongyado
    info: 生命不止，折腾不息
    url: http://dongyado.com/
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=100
  - name: OrangeCoder
    info: android ffmpeg nodejs gradle
    url: http://orangecoder.com/
    avatar: https://avatars0.githubusercontent.com/u/2263785?v=3&s=100
  - name: EverET
    info: 好记性不如烂笔头
    url: http://everet.org/about-me/
    avatar: https://avatars1.githubusercontent.com/u/1559563?v=3&s=100
  - name: 题叶
    info: FP, GUI, Writing
    url: http://tiye.me/
    avatar: https://avatars2.githubusercontent.com/u/449224?v=3&s=100
  - name: McChen
    info: Stay Hungry, Stay Foolish
    url: http://mcchen.club/
    avatar: https://avatars0.githubusercontent.com/u/8033333?v=3&s=100


project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: beside
    url: https://github.com/forsigner/beside
    intro: I need you beside me
  - type: personal
    name: web-fontmin
    url: https://github.com/forsigner/web-fontmin
    intro: 字体子集化，在线提取你需要的字体
  - type: personal
    name: magic-check
    url: https://github.com/forsigner/magic-check
    intro: Beautify Radio and Checkbox with pure CSS
  - type: personal
    name: nice-bar
    url: https://github.com/forsigner/nice-bar
    intro: A nice and lightweight scrollbar
  - type: personal
    name: angular-nice-bar
    url: https://github.com/forsigner/angular-nice-bar
    intro: A nice and lightweight scrollbar in Angular
  - type: personal
    name: fo-popover
    url: https://github.com/forsigner/fo-popover
    intro: A nice popover for Angular
  - type: personal
    name: fo-tooltip
    url: A nice tooltip for Angular
    intro: https://github.com/forsigner/fo-tooltip
  - type: personal
    name: fo-modal
    url: https://github.com/forsigner/fo-modal
    intro: A nice modal for Angular
  - type: personal
    name: mocer
    url: https://github.com/forsigner/mocer
    intro: Setup a mock server easily
  - type: personal
    name: node-pngdefry
    url: https://github.com/forsigner/node-pngdefry
    intro: Repairing iPhone fried PNGs using Node.js
  - type: personal
    name: ng-simditor
    url: https://github.com/forsigner/ng-simditor
    intro: Angular directive for simditor
